Realsense2
robotology/robots-configuration pull request #250
Opened 2021-03-31 16:44 UTC by ste93

added realsense2 configuration for the robot with ros and yarp wrappers and ros point cloud wrapper

2021-03-31 16:59 UTC, pattacini approved these changes
Thanks @ste93 for the addition 👍🏻 
Awaiting @randaz81 's review.

2021-03-31 17:32 UTC, randaz81 requested changes

2021-03-31 17:32 UTC, randaz81 commented on CER04/wrappers/camera/rgbdsensor_ros.xml
> +    <param name="period"> 100                 </param>
The goal is to achieve 30FPS. seconds (0.033) or milliseconds (33)?

2021-03-31 17:32 UTC, randaz81 commented on CER04/wrappers/camera/rgbdsensor_yarp.xml
> +    <param name="period"> 100                 </param>
The goal is to achieve 30FPS. seconds (0.033) or milliseconds (33)?

2021-03-31 17:32 UTC, randaz81 commented on CER04/wrappers/camera/pointcloudsensor_ros.xml
> +    <param name="period"> 100                 </param>
Value 100 should be checked.

2021-03-31 17:32 UTC, randaz81 commented on CER04/wrappers/camera/rgbdsensor_ros.xml
> +    <param name="colorTopicName">    /camros/color/raw_image    </param>
I recommend the default prefix /camera instead of /camros

2021-03-31 17:32 UTC, randaz81 commented on CER04/wrappers/camera/rgbdsensor_ros.xml
> +    <param name="nodeName">    /camros/rgbdwrapperros    </param>
maybe better /camera/rgbdSensor_nws_ros ?

2021-03-31 17:32 UTC, randaz81 commented on CER04/wrappers/camera/rgbdsensor_yarp.xml
> +    <param name="name">    /RGBDSensorWrapper_yarp    </param>
/cer/realsense

2021-03-31 17:32 UTC, randaz81 commented on CER04/wrappers/camera/pointcloudsensor_ros.xml
> +    <param name="pointCloudTopicName">   /RGBD2PointCloud   </param>
/RGBDPointCloud2? or ROS default name: /camera/depth/color/points

2021-03-31 17:32 UTC, randaz81 commented on CER04/wrappers/camera/pointcloudsensor_ros.xml
> +    <param name="nodeName">    /rgbdtopointcloudsensor_ros_node    </param>
/camera/rgbdPointCloud_nws_ros

2021-03-31 17:34 UTC, randaz81 commented
Just some suggestions to standardize the name of the opened port/topics

2021-04-01 07:51 UTC, ste93 commented
can it be good to standardise the names between ros and yarp? so maybe call the ros wrapper /cer/realsense/color/raw_image or /cer/realsense_ros/color/raw_image ?

2021-04-01 18:03 UTC, pattacini commented
@randaz81 I think that @ste93 has addressed all the points.

2021-04-07 10:21 UTC, randaz81 commented
The following PRs are need to test this on the robot:
- https://github.com/robotology/yarp-device-realsense2/pull/9
- https://github.com/robotology/yarp/pull/2524

2021-04-16 13:11 UTC, pattacini commented
@randaz81 @ste93 any updates on this?

2021-04-19 09:14 UTC, ste93 commented
I think @randaz81 wants to wait the merge of https://github.com/robotology/yarp-device-realsense2/pull/9 since without it there are problems with the realsense

2021-04-27 10:29 UTC, pattacini commented
Both the required PR's have been merged.
I think we can proceed now @randaz81 @ste93.

2021-04-30 11:31 UTC, pattacini commented
Gentile reminder 🔔
@ste93 @randaz81

2021-04-30 13:04 UTC, pattacini commented
Unfortunately, this PR has exploded after the latest commit.
In no way I'm going to merge it as it is now 😄

Better off push-forcing and make it reasonable again.

2021-04-30 13:05 UTC, pattacini requested changes
Unfortunately, this PR has exploded after the latest commit.
In no way I'm going to merge it as it is now 😄

Better off push-forcing and make it reasonable again.

2021-04-30 13:07 UTC, pattacini commented
If you feel more confident @ste93, we can decide to close this PR and do the work from scratch given that we're dealing with a few files only.

2021-05-03 08:23 UTC, ste93 commented
corrected the push, it was wrong base branch

2021-05-03 09:36 UTC, pattacini commented on R1SN003/wrappers/camera/pointcloudsensor_ros.xml
> +    <param name="period"> 0.033 </param>
Hi @ste93 

I've seen that this period is given in seconds (I think YARP device drivers will comply w/ seconds in the future) whereas the others are given in milliseconds (standard way as of now).

Is this mixed-mode intended?

If so, I'll be eager to merge the PR.

2021-05-03 09:41 UTC, ste93 commented
hi @pattacini , yes the mixed mode is intended since future YARP device drivers will comply w/ seconds in the future and the point cloud driver follows this, while rgbd drivers doesn't follow this yet. This will be available in next yarp release (maybe an issue can be opened to keep track of the future changes?)

2021-05-03 09:49 UTC, pattacini commented
Thanks @ste93 for the clarification 👍🏻 

>maybe an issue can be opened to keep track of the future changes?

It's a massive change involving many files in this repo and as such it will be attacked properly.

2021-05-03 09:49 UTC, pattacini approved these changes

2021-05-03 09:50 UTC, merged