iCub: Update neck_pitch and neck_roll position PIDs in head version > = 2.0
robotology/robots-configuration pull request #447
Opened 2023-02-28 15:58 UTC by martinaxgloria

The updated PID values are obtained by an automatic and robust tuning process described and simulated [here](https://github.com/icub-tech-iit/study-icub-head/tree/sim). 
These values were then tested on iCubGenova02 and iCubGenova09.

2023-02-28 16:10 UTC, pattacini requested changes
`iCubGenova09` doesn't seem to be up-to-date.

See https://github.com/robotology/robots-configuration/blob/devel/iCubGenova09/hardware/motorControl/head-eb20-j0_1-mc.xml#L50-L52.

Would you mind taking this robot into account as well?

2023-02-28 16:25 UTC, martinaxgloria commented
`iCubGenova07`, `iCubGenova09` and `iCubGenova10` are now up-to-date as well.

2023-03-01 07:43 UTC, pattacini approved these changes

2023-03-01 09:32 UTC, pattacini approved these changes

2023-03-01 09:32 UTC, merged