Clean-up grabberDual
robotology/robots-configuration pull request #469
Opened 2023-04-04 12:00 UTC by martinaxgloria

As per title, this PR contains the cleaning up of the leftovers of `grabberDual` service.

2023-04-04 12:32 UTC, Nicogene requested changes

2023-04-04 12:32 UTC, Nicogene commented on experimentalSetups/head_face-v3/camera/dragonfly2_config_left.ini
> +capabilities RAW
For `dragonfly2` the parameter `capabilities` as to be set to `COLOR` or not set (`COLOR` is default)

2023-04-04 12:53 UTC, pattacini commented
We need to address also `icub-main` apps to replace references to the dual configurations.

2023-04-04 16:14 UTC, martinaxgloria commented
Ok @pattacini tomorrow I will check for the other references in icub-main.

2023-04-05 15:33 UTC, martinaxgloria commented
I opened the PR for the clean-up of `dualGrabber` references in icub-main.

- https://github.com/robotology/icub-main/pull/861

2023-04-05 20:17 UTC, pattacini requested changes
Other files to be removed.

2023-04-05 20:17 UTC, pattacini commented on iCubGenova11/camera/this doesn't needed/ServerGrabberDualDragon.ini
This file needs to be removed outright.

2023-04-05 20:17 UTC, pattacini commented on iCubGenova11/camera/this doesn't needed/ServerGrabberDualDragonBayer640_480.ini
This file needs to be removed outright.

2023-04-06 06:54 UTC, martinaxgloria commented on iCubGenova11/camera/this doesn't needed/ServerGrabberDualDragon.ini
Ok, I will remove the entire folder then.

2023-04-06 08:09 UTC, Nicogene commented
> If I interpreted @Nicogene's comment correctly, all `capabilities` need to be replaced from `RAW` to `COLOR`.

We aligned T2T, for `dragonfly2` is ok also to not specify `capabilities`, since `COLOR` is the default.

2023-04-06 08:10 UTC, Nicogene requested changes

2023-04-06 08:10 UTC, Nicogene commented on experimentalSetups/head_face-v3/camera/dragonfly2_config_right.ini
> +capabilities RAW
Probably a find/replace error, `capabilities RAW` has to be removed here and for the other `dragonfly2`

2023-04-06 08:28 UTC, Nicogene approved these changes
Obviously it is impossible to check all the files, but they seems ok overall now 👍🏻 

We need a test on a robot before merging

2023-04-06 09:45 UTC, pattacini approved these changes

2023-04-06 11:47 UTC, Nicogene requested changes
@pattacini good catch!

> What's the strategy with R1?

We should change `grabberDual` with `frameGrabber_nws_yarp` 

cc @martinaxgloria

2023-04-06 12:40 UTC, martinaxgloria commented
Today I tested the changes on `iCubGenova11` and I was able to open both cameras. 

![photo_5870860122425769501_w](https://user-images.githubusercontent.com/114698424/230380998-1cab1709-8080-4fe4-8ddb-3bd9204ec5f4.jpg)

2023-04-06 12:53 UTC, Nicogene approved these changes

2023-04-06 12:54 UTC, merged