Feature/temperature reading
robotology/robots-configuration pull request #597
Opened 2023-11-29 16:29 UTC by MSECode

This PR brings the following changes:
- update the ergocubSN001 configuration files with the `TemperatureSensorType` values for all the necessary joints and set it to NONE so that we have back-compatibility and add the `hardwareTemperatureLimits` and the `warningTemperatureLimits` and keep them commented for back-compatibility (default suggested values are provided in the commented line in the file)
- update the Template v6 with all the necessary info for filling the conf files with the new parameters

2023-11-29 16:30 UTC, MSECode commented
cc: @valegagge

2023-12-01 08:05 UTC, valegagge requested changes
Just some minor changes.
thank you

2023-12-01 08:05 UTC, valegagge commented on ergoCubSN001/hardware/motorControl/left_leg-eb8-j0_3-mc.xml
> +        <param name="maxOutput">               12000               12000       12000    16000      </param>
Please reset 10000

2023-12-01 08:05 UTC, valegagge commented on ergoCubSN001/hardware/motorControl/left_leg-eb9-j4_5-mc.xml
> +        <!-- <param name="hardwareTemperatureLimits">    110                 110                </param>
Please put motorPwmLimit above temperature limits

2023-12-01 08:05 UTC, valegagge commented on ergoCubSN001/hardware/motorControl/right_leg-eb6-j0_3-mc.xml
> +        <param name="motorPwmLimit">            16000               16000     16000    16000    </param>
Please put motorPwmLimit above temperature limits

2023-12-01 08:05 UTC, valegagge commented on ergoCubSN001/hardware/motorControl/right_leg-eb6-j0_3-mc.xml
> +        <param name="maxOutput">               12000               11000     12000    16000    </param>
Please restore the old value

2023-12-01 08:05 UTC, valegagge commented on ergoCubSN001/hardware/motorControl/right_leg-eb7-j4_5-mc.xml
> +        <!-- <param name="hardwareTemperatureLimits">     110                110                </param>
Please put motorPwmLimit above temperature limits

2023-12-01 08:05 UTC, valegagge commented on ergoCubSN001/hardware/motorControl/torso-eb5-j0_2-mc.xml
> +        <param name="warningTemperatureLimits">  90                 90                    90                </param>       keep commented until TemperatureSensorType is not ENABLE by setting it diffe
Please put motorPwmLimit above temperature limits

2023-12-01 08:12 UTC, pattacini requested changes
The CI is failing repeated errors of the form:
```console
[ERROR] HasTempSensor parameter not found for board torso-eb5-j0_2 in bottle "2FOC" (Verbose 0 0 0) (AutoCalibration 0 0 0) (HasHallSensor 0 0 0) (TemperatureSensorType NONE NONE NONE) (HasRotorEncoder 1 1 1) (HasRotorEncoderIndex 1 1 1) (HasSpeedEncoder 0 0 0) (RotorIndexOffset 155 134 328) (MotorPoles 8 8 8)
[ERROR] BOARD torso-eb5-j0_2 (IP 10.0.1.5)  Missing motion control parameters in config file
[ERROR] |yarp.dev.PolyDriver|torso-eb5-j0_2-mc| Driver <embObjMotionControl> was found but could not open
```

Here's the complete log:
- [dry-run_log_ergoCubSN001_dev.txt](https://github.com/robotology/robots-configuration/files/13522656/dry-run_log_ergoCubSN001_dev.txt)

2023-12-01 08:34 UTC, MSECode commented
> The CI is failing with repeated errors of the type:
> 
> ```
> [ERROR] HasTempSensor parameter not found for board torso-eb5-j0_2 in bottle "2FOC" (Verbose 0 0 0) (AutoCalibration 0 0 0) (HasHallSensor 0 0 0) (TemperatureSensorType NONE NONE NONE) (HasRotorEncoder 1 1 1) (HasRotorEncoderIndex 1 1 1) (HasSpeedEncoder 0 0 0) (RotorIndexOffset 155 134 328) (MotorPoles 8 8 8)
> [ERROR] BOARD torso-eb5-j0_2 (IP 10.0.1.5)  Missing motion control parameters in config file
> [ERROR] |yarp.dev.PolyDriver|torso-eb5-j0_2-mc| Driver <embObjMotionControl> was found but could not open
> ```
> 
> Here's the complete log:
> 
> * [dry-run_log_ergoCubSN001_dev.txt](https://github.com/robotology/robots-configuration/files/13522656/dry-run_log_ergoCubSN001_dev.txt)

I saw that.
Btw, just one info, on which superbuild version is running the CI. I mean, on which icub-main version it is build when running the CI? Because, on the last PR I developed for icub-main, I set that the configuration parameter `HasTempSensor` is not mandatory anymore, so it should not complain for that.
Let me know.

2023-12-01 09:19 UTC, pattacini approved these changes
CI now is passed ✅ 
@MSECode, please address @valegagge's comments to proceed further.

2023-12-01 11:35 UTC, MSECode commented
It should be now ready for the review

2023-12-01 11:46 UTC, valegagge commented
Hi @MSECode,
All is fine! 🚀 thank you!

cc @pattacini

2023-12-01 11:55 UTC, pattacini approved these changes

2023-12-01 11:55 UTC, merged