Add friction + coulomb + threshold parameters
robotology/robots-configuration pull request #599
Opened 2023-12-07 08:28 UTC by sgiraz

**What's new:**
- Remove the old `kbemf` torque parameter in favor of the new torque control parameters:
  - `viscousPos`
  - `viscousNeg`
  - `coulombPos`
  - `coulombNeg`
  - `verlocityThres`

The new friction compensation law is the following one (see also the [source code][1]):

```cpp
float PID_do_friction_comp(PID *o, float32_t vel_fbk, float32_t trq_ref)
{
    const float32_t MICRO { 1000000.0 }; // conversion from Nm into microNm
    const float32_t coulomb_pos_converted = o->coulomb_pos_val * MICRO;
    const float32_t coulomb_neg_converted = o->coulomb_neg_val * MICRO;
    
    const float32_t viscous_neg = o->viscous_neg_val * vel_fbk;
    const float32_t viscous_pos = o->viscous_pos_val * vel_fbk;
    
    if (vel_fbk <= -o->velocityThres_val)
    {
        return o->Ktau*(-coulomb_neg_converted + viscous_neg + o->Kff*trq_ref);
    }
    else if (vel_fbk > o->velocityThres_val)
    {
        return o->Ktau*(coulomb_pos_converted + viscous_pos + o->Kff*trq_ref);
    }
    else
    {
        return o->Ktau*(o->Kff*trq_ref);
    }
}
```

**Note:**
- The following robots will be affected by this changes:

| robot                          |
| :----------------------: |
| ergoCubSN000           | 
| ergoCubSN001            |
| iCubEdinburg01           | 
| iCubErzelli01                | 
| iCubErzelli02                | 
| iCubGenova02             |
| iCubGenova07             |      
| iCubGenova08             |
| iCubGenova10             |
| iCubGenova11             | 
| iCubLisboa01               | 
| iCubNancy01               | 
| iCubPargue01              |
| iCubShanghai01          | 
| iCubShenzhen01         |
| iCubSingapore01        | 
| iCubTemplates            |
| iCubValparaiso01        | 
| iCubWaterloo01          |
| iCubZagreb01             |

cc @isorrentino @marcoaccame @Nicogene 

[1]: https://github.com/robotology/icub-firmware/blob/89299e156937c709f0381d9578cfbca7e0244a5a/emBODY/eBcode/arch-arm/embobj/plus/mc/Pid.c#L206C1-L234C2

2023-12-09 15:29 UTC, pattacini requested changes
Hi @sgiraz 

To guarantee back-compatibility, we need to make sure that the values of `viscousPos` and `viscousNeg` equate to the values of `kbemf`[^1]. This is true for most of the robots but NOT for those where `kbemef` <> 0.

Thus, there are robots requiring a fix. 

[^1]: See https://github.com/robotology/icub-firmware/pull/410/files.

2023-12-12 15:31 UTC, sgiraz commented
> Hi @sgiraz
> 
> To guarantee back-compatibility, we need to make sure that the values of `viscousPos` and `viscousNeg` must equate the values of `kbemf`[1](#user-content-fn-1-cb1a9d588af34cdadf5a586947ec2d18). This is true for most of the robots but NOT for those where `kbemef` <> 0.
> 
> Thus, there are robots requiring a fix.
> 
> ## Footnotes
> 1. See https://github.com/robotology/icub-firmware/pull/410/files. [↩](#user-content-fnref-1-cb1a9d588af34cdadf5a586947ec2d18)

Hi @pattacini,

Changes applied! Thanks for your feedback.

2023-12-12 15:42 UTC, pattacini approved these changes
Thank you @sgiraz!

I'll wait a bit for @isorrentino and/or @GiulioRomualdi to check the changes for ergoCub before merging.

2023-12-13 07:28 UTC, pattacini commented
/remind December 18, merge the PR.

2023-12-13 15:42 UTC, isorrentino approved these changes

2023-12-13 15:44 UTC, isorrentino commented
The modifications seem okay. Obviously, the parameters provided are not the ones that make the joints work in torque, but with those values we are confident that nothing will happen if the torque control is activated.

2023-12-13 15:51 UTC, merged