IMU sensors - Include alljoints-inertials_wrapper/remapper in YRI xml files
robotology/robots-configuration pull request #640
Opened 2024-04-11 14:40 UTC by martinaxgloria

As pointed out by @traversaro [here](https://github.com/icub-tech-iit/ergocub-software/pull/232#issuecomment-2039771072), the  files that expose via multipleanalogsensorsremapper the orientation measurements of the available IMUs are now included in the XML used by the yarprobotinterface

This PR will complete https://github.com/robotology/robots-configuration/issues/636

2024-04-11 15:06 UTC, pattacini requested changes
Hi @martinaxgloria 
CI is failing.

2024-04-11 15:12 UTC, martinaxgloria commented
Probably I'm missing some configuration files, I'll take a look into

2024-04-12 08:07 UTC, martinaxgloria commented
As expected, the CI was falling due to some missing configuration files. Moreover, I noticed that the dry-run checks only the XML that the YRI uses by default, that is the one under `yarprobotinterface.ini`. Since for the other XML there's no CI check (for example, for `ergocub_wbd.xml` or for `ergocub_all_ros2.xml`, but also some iCubs have more than one YRI launch file), what about adding the alljoints-inertials_wrapper/remapper only in the main yarprobotinterface XML file? Or are there other files that are used and that could be worth manually maintaining them? 

cc @traversaro @Nicogene @pattacini

2024-04-12 08:24 UTC, traversaro commented
Ok, I think I did not get your question.

2024-04-12 09:22 UTC, martinaxgloria commented
Aligned with @traversaro t2t, we decided to expose IMU measurements only in the yri default xml for the iCubs, while for ergoCubSN001 and ergoCubSN002 in all `ergocub_*.xml`.

cc @Nicogene @pattacini

2024-04-12 09:54 UTC, pattacini approved these changes
Thanks heaps for the fix, @martinaxgloria 🚀

2024-04-12 09:55 UTC, merged