ergoCubSN001 - update network file
robotology/robots-configuration pull request #652
Opened 2024-05-16 13:44 UTC by davidetome

This PR updates the network file of the robot

cc @valegagge

2024-05-16 15:10 UTC, pattacini requested changes
Hi @davidetome 

Could you provide some insights underlying this big change?
Also, would it be worth covering the other ergoCub as well?

Possibly, there's one typo requiring attention. Didn't spot others but, please, check it.

2024-05-16 15:10 UTC, pattacini commented on ergoCubSN001/network.ergoCubSN001.xml
> +        <board type='foc' name="foc.7`.2">
There could be a typo here.

2024-05-17 08:35 UTC, davidetome commented
> Hi @davidetome
> 
> Could you provide some insights underlying this big change? Also, would it be worth covering the other ergoCub as well?
> 
> Possibly, there's one typo requiring attention. Didn't spot others but, please, check it.

Ciao @pattacini !!!
 
   I noticed that the [network ](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/network.ergoCubSN001.xml)file was not aligned to the real [architecture ](https://github.com/icub-tech-iit/electronics-wiring/blob/master/ergocub1/ergocub1.2/pdf/ergoCub1.2_Logic_17929_1.2.0.pdf),

I just fixed some errors and checked again w/ the schematic. 

Also SN002 is not correct (probably copied when the folder was created)

cc @valegagge @AntonioConsilvio

2024-05-17 08:38 UTC, pattacini commented
> I noticed that the [network ](https://github.com/robotology/robots-configuration/blob/devel/ergoCubSN001/network.ergoCubSN001.xml)file was not aligned to the real [architecture ](https://github.com/icub-tech-iit/electronics-wiring/blob/master/ergocub1/ergocub1.2/pdf/ergoCub1.2_Logic_17929_1.2.0.pdf),
> 
> I just fixed some errors and checked again w/ the schematic.

Superb! Thanks heaps!


> Also SN002 is not correct (probably copied when the folder was created)

Then, it'd be great if we could fix it up as well.

@AntonioConsilvio, you may consider checking these things out for SN000, which is by us these days.

2024-05-17 08:53 UTC, davidetome commented
@pattacini @AntonioConsilvio , as suggested by @valegagge , I also fixed SN002 with the last commit 👍🏼

2024-05-17 08:58 UTC, pattacini commented
Thanks @davidetome 🚀

2024-05-17 08:59 UTC, pattacini approved these changes
Awaiting the PR to be put in ready for review.

2024-05-17 09:11 UTC, AntonioConsilvio commented
Hi! Well done @davidetome.

I'd just like to add that some boards are actually not connected to each other.

For example, the `10.0.1.2` board, has no boards before it, because it's connected to the ETH switch (Gigablox) so it might make sense to edit line 66 in exactly the same way as 10.0.1.5 (i.e. without the `prev` parameter - line 266)? 
Similarly, 10.0.1.21 has no boards after it, so it might make sense to remove the `next` parameter?

Other boards might have this little problem, in the architecture the ETH switch is represented like this:

![image](https://github.com/robotology/robots-configuration/assets/114915464/4427a600-09f1-47bf-99c9-7a55f52956e3)

cc @pattacini

2024-05-17 09:17 UTC, davidetome commented
> Hi! Well done @davidetome.
> 
> I'd just like to add that some boards are actually not connected to each other.
> 
> For example, the `10.0.1.2` board, has no boards before it, because it's connected to the ETH switch (Gigablox) so it might make sense to edit line 66 in exactly the same way as 10.0.1.5 (i.e. without the `prev` parameter - line 266)? Similarly, 10.0.1.21 has no boards after it, so it might make sense to remove the `next` parameter (line 56)?
> 
> Other boards might have this little problem, in the [architecture](https://github.com/icub-tech-iit/electronics-wiring-public/blob/master/ergocub1/ergocub1.2/pdf/ergoCub1.2_Logic_17929_1.2.0.pdf) the ETH switch is represented like this:
> 
> ![image](https://private-user-images.githubusercontent.com/114915464/331533030-4427a600-09f1-47bf-99c9-7a55f52956e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5Mzc2MjAsIm5iZiI6MTcxNTkzNzMyMCwicGF0aCI6Ii8xMTQ5MTU0NjQvMzMxNTMzMDMwLTQ0MjdhNjAwLTA5ZjEtNDdiZi05OWM5LTdhNTVmNTI5NTZlMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QwOTE1MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTUyYzIzMGRiOGU2NTU4YTJmMDcyZTE5MTNjOWRmNGI4MWRjNWFhYTdkYzU3YTc1MjFkYTc0ZjVkOTEyYzRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rSw-imzewN6rE1R0SFezJxk0P9QhtgJIgJuHkDf_leY)
> 
> cc @pattacini

ciao @AntonioConsilvio , it doesn't matter...the previous and next tag are only for info when reading the file.
you can also not declare them and the script runs  the same

2024-05-17 09:28 UTC, davidetome commented
@AntonioConsilvio , just to make you happy I just fixed them with the last commit 😄  👍🏼

2024-05-17 10:33 UTC, AntonioConsilvio approved these changes

2024-05-22 20:00 UTC, valegagge approved these changes
LGTM

2024-05-24 07:37 UTC, merged